// ============================================================
// pi-swarm-dao — Automated PR Generation (Proposal #11)
// ============================================================
// Generates feature branches, commits scaffolding, and opens
// draft PRs from executed proposals.
// ============================================================

import { execFileSync } from "node:child_process";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { Proposal } from "../types.js";
import { PROPOSAL_TYPE_LABELS } from "../types.js";
import { getIssueNumber } from "../github-persistence.js";

// ── Git/gh Helpers ───────────────────────────────────────────

const git = (...args: string[]): string => {
  try {
    return execFileSync("git", args, {
      cwd: process.cwd(),
      encoding: "utf-8",
      maxBuffer: 5 * 1024 * 1024,
      timeout: 30_000,
    }).trim();
  } catch (err: any) {
    const msg = err?.stderr?.toString() || err?.message || "";
    throw new Error(`git ${args.join(" ")} failed: ${msg.slice(0, 500)}`);
  }
};

const gh = (...args: string[]): string => {
  try {
    return execFileSync("gh", args, {
      cwd: process.cwd(),
      encoding: "utf-8",
      maxBuffer: 5 * 1024 * 1024,
      timeout: 30_000,
    }).trim();
  } catch (err: any) {
    const msg = err?.stderr?.toString() || err?.message || "";
    throw new Error(`gh ${args.join(" ")} failed: ${msg.slice(0, 500)}`);
  }
};

// ── Branch Naming ────────────────────────────────────────────

/** Generate a branch name from a proposal. */
const branchName = (proposal: Proposal): string => {
  const prefix: Record<string, string> = {
    "product-feature": "feat",
    "security-change": "security",
    "technical-change": "chore",
    "release-change": "release",
    "governance-change": "gov",
  };
  const pre = prefix[proposal.type] || "feat";
  // Slugify title: lowercase, replace non-alphanumeric with -, collapse
  const slug = proposal.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
  return `${pre}/${proposal.id}-${slug}`;
};

// ── PR Body Builder ──────────────────────────────────────────

const buildPRBody = (proposal: Proposal): string => {
  const typeLabel = PROPOSAL_TYPE_LABELS[proposal.type];
  let body = `## ${typeLabel}\n\n`;
  body += `**Proposal:** #${proposal.id}\n`;
  body += `**Title:** ${proposal.title}\n`;
  body += `**Type:** ${proposal.type}\n\n`;

  body += `### Description\n${proposal.description.slice(0, 2000)}\n\n`;

  if (proposal.synthesis) {
    body += `### Deliberation Summary\n${proposal.synthesis.slice(0, 1500)}\n\n`;
  }

  if (proposal.executionResult) {
    body += `### Execution Plan\n${proposal.executionResult.slice(0, 2000)}\n\n`;
  }

  // Link to GitHub issue if available
  const issueNumber = getIssueNumber(proposal.id);
  if (issueNumber) {
    body += `### Tracking\nCloses #${issueNumber}\n\n`;
  }

  body += `---\n*Auto-generated by DAO Swarm — Proposal #${proposal.id}*`;
  return body;
};

// ── Scaffolding ──────────────────────────────────────────────

/** File templates for different proposal types */
const FILE_TEMPLATES: Record<string, Record<string, string>> = {
  "product-feature": {
    "SCOPE.md": `# Scope\n\n## In Scope\n- \n\n## Out of Scope\n- \n`,
    "tests/placeholder.test.ts": `// Tests for proposal implementation\nimport { describe, it, expect } from "vitest";\n\ndescribe("Proposal implementation", () => {\n  it("should pass placeholder test", () => {\n    expect(true).toBe(true);\n  });\n});\n`,
  },
  "technical-change": {
    "ARCHITECTURE.md": `# Architecture Change\n\n## Current State\n\n## Proposed Change\n\n## Migration Steps\n\n## Rollback Plan\n`,
    "tests/placeholder.test.ts": `// Tests for technical change\nimport { describe, it, expect } from "vitest";\n\ndescribe("Technical change", () => {\n  it("should pass placeholder test", () => {\n    expect(true).toBe(true);\n  });\n});\n`,
  },
  "security-change": {
    "SECURITY.md": `# Security Change\n\n## Threat Model\n\n## Mitigation\n\n## Verification Steps\n`,
    "tests/security.test.ts": `// Security tests\nimport { describe, it, expect } from "vitest";\n\ndescribe("Security change", () => {\n  it("should pass security verification", () => {\n    expect(true).toBe(true);\n  });\n});\n`,
  },
  "release-change": {
    "RELEASE.md": `# Release Notes\n\n## Version\n\n## Changes\n\n## Migration Guide\n\n## Breaking Changes\n`,
  },
  "governance-change": {
    "GOVERNANCE.md": `# Governance Change\n\n## Current Policy\n\n## New Policy\n\n## Rationale\n\n## Impact\n`,
  },
};

/** Generate scaffolding files for a proposal type. */
const generateScaffolding = (proposal: Proposal): Map<string, string> => {
  const files = new Map<string, string>();
  const templates = FILE_TEMPLATES[proposal.type] || FILE_TEMPLATES["product-feature"];

  for (const [path, content] of Object.entries(templates)) {
    files.set(path, content);
  }

  return files;
};

// ── Public API ───────────────────────────────────────────────

export interface PRGenerationResult {
  branch: string;
  filesCreated: string[];
  prUrl: string;
  prNumber: number;
  commitSha: string;
}

/**
 * Generate a draft PR from an executed proposal.
 * Creates a feature branch, writes scaffolding, commits, and opens a draft PR.
 */
export const generatePR = (proposal: Proposal): PRGenerationResult => {
  // 1. Get current branch (should be main)
  const currentBranch = git("branch", "--show-current");

  // 2. Create feature branch
  const branch = branchName(proposal);
  git("checkout", "-b", branch);

  // 3. Generate scaffolding files
  const files = generateScaffolding(proposal);
  const filesCreated: string[] = [];

  for (const [filePath, content] of files) {
    const fullPath = join(process.cwd(), filePath);
    const dir = join(fullPath, "..");

    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }

    writeFileSync(fullPath, content, "utf-8");
    filesCreated.push(filePath);
  }

  // 4. Commit scaffolding
  git("add", ...filesCreated);
  git("commit", "-m", `feat(proposal-${proposal.id}): scaffold for ${proposal.title}`);

  const commitSha = git("rev-parse", "--short", "HEAD");

  // 5. Push branch
  try {
    git("push", "-u", "origin", branch);
  } catch {
    // If push fails (e.g., remote doesn't support push), try with --set-upstream
    git("push", "origin", branch);
  }

  // 6. Create draft PR
  const prBody = buildPRBody(proposal);
  const prTitle = `${PROPOSAL_TYPE_LABELS[proposal.type]} #${proposal.id}: ${proposal.title}`;

  const prResult = gh(
    "pr", "create",
    "--title", prTitle,
    "--body", prBody,
    "--draft",
    "--base", currentBranch,
  );

  // Parse PR URL and number
  const prUrl = prResult.split("\n").find(l => l.includes("github.com")) || prResult;
  const prMatch = prResult.match(/#(\d+)/);
  const prNumber = prMatch ? parseInt(prMatch[1], 10) : 0;

  // 7. Switch back to original branch
  git("checkout", currentBranch);

  return {
    branch,
    filesCreated,
    prUrl,
    prNumber,
    commitSha,
  };
};

/**
 * Check if a PR already exists for a proposal.
 */
export const findExistingPR = (proposalId: number): { number: number; url: string; state: string } | null => {
  try {
    const result = gh(
      "pr", "list",
      "--head", `*proposal-${proposalId}*`,
      "--json", "number,url,state",
      "--state", "all",
      "--limit", "1",
    );

    if (!result) return null;

    const prs = JSON.parse(result);
    if (prs.length === 0) return null;

    return {
      number: prs[0].number,
      url: prs[0].url,
      state: prs[0].state,
    };
  } catch {
    return null;
  }
};
